apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: tarasmti/crs_auth
          env:
            - name: JWT_SECRET_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_ACCESS_TOKEN
            - name: JWT_SECRET_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_REFRESH_TOKEN
          # resources:
          #   limits:
          #     cpu: 4m
          #     memory: 4000Mi
          #   requests:
          #     cpu: 4m
          #     memory: 4000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000
